#docker-compose down --rmi all --volumes
##docker-compose up --no-deps web-node
version: "3.8"
services:
  web-node:
    build: .
    command: npm start
    ports:
      - target: 3000
        published: 8081
    networks:
      - my-web-net
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app        
  redis-service:
    image: "redis:alpine"
    networks:
      - my-web-net

networks:
  my-web-net:

volumes:
  site-volume:
